### ISSUE TITLE
''Platform Rewards'' Question

### ISSUE THREAD

**Issue by Major-Cryptic** [goatfungus/NMSSaveEditor#846]
So there is the switch limited exclusive in the section but is it actually doable to claim them for the PC or no? cause I am really confuse as how to do it if we can , the items are nice tbh. Thanks for an answer!

**Comment by BrodieCole** [comment]
I am curious of this as well. I tried it and nothing happened for me. I couldn't get any of the account items to show on the current "Singularity" build though. So I wonder if NMS patched these possibly...

**Comment by Devilin-Pixy** [comment]
Ok, so here is how to do it, because just clicking those 2 checkboxes for it on the Account tab is not working.

You still have to do the above, but you also need to edit to include both rewards in the GCUSERSETTINGSDATA.MXML within your SETTINGS folder. Look for the 'UnlockedPlatformRewards' section and edit it to be as follows, or if other platform rewards are already present, include just the two new ones, and save it:
```xml
	<Property name="UnlockedPlatformRewards">
		<Property name="UnlockedPlatformRewards" value="SW_PREORDER" />
		<Property name="UnlockedPlatformRewards" value="SW_PREORDER2" />
	</Property>
```
Important! You have to then launch No Man's Sky while disconnected from the internet, or the Account data edits will revert. (the edits in GCUSERSETTINGSDATA appear to stick for this). You claim both rewards at the QS Bot aboard the Anomaly (Special Rewards).

![20230705214025_1](https://github.com/goatfungus/NMSSaveEditor/assets/7830771/5def56d5-8a35-45b9-9382-e8f8add92d29)

**Comment by Devilin-Pixy** [comment]
@goatfungus Maybe it would be possible to make this work correctly?

**Comment by Major-Cryptic** [comment]
> ```
> <Property name="UnlockedPlatformRewards">
> 		<Property name="UnlockedPlatformRewards" value="SW_PREORDER" />
> 		<Property name="UnlockedPlatformRewards" value="SW_PREORDER2" />
> 	</Property>
> ```

THANK YOU SO MUCH , dont know how you found it but damn finally I can have them haha! and yeah would be nice an easier way to get them or some explanation in the FAQ maybe , thanks again! hope people that want them will find this post!

**Comment by BrodieCole** [comment]
Wow! Thank you! Yeah this is awesome! I am wondering if I need to just do the exact same thing with the expedition awards too since just simply checking those or the twitch reward boxes don't currently work for me

**Comment by Devilin-Pixy** [comment]
@BrodieCole For expedition and Twitch rewards this should not be needed. You may however check if the reward IDs are already present in your Save data in the two locations below (Raw JSON): 
* PersistentPlayerData > RedeemedSeasonRewards

or

* PersistentPlayerData > KnownSpecials

If that is the case, you will not be able to claim on that save.

**Comment by ukmerlin** [comment]
@Devilin-Pixy For the Expedition & Twitch rewards are you saying that they need to be deleted from all three locations? I too had added them in NMSE but they were not redeemable at the store, disconnected from the network. I don't recall whether they were listed as "not owned". I may also have some Twitch items marked as redeemed (owned) but I don't actually have them.

**Comment by Devilin-Pixy** [comment]
@ukmerlin It would not make sense for Twitch Rewards to be in the RedeemedSeasonRewards, but it does not hurt checking for those Twitch IDs and remove them there if present. Basically if the game finds the ID as known or redeemed in the **save**, it will fail to reward it at the QS shop, even if marked as unlocked on the **account**. This is done to prevent unlocking multiple times on the same save.

**Comment by Devilin-Pixy** [comment]
@ukmerlin You mean a list of IDs? I do have those, but that is a lot of them. I have them shared in a few places. Could share them on the Atlas CSD forum if you wish.

**Comment by Gir-Thing** [comment]
doesnt work anymore after worlds part 2 update. the game now automatically updates the settings and corrects errors regardless of internet connection. worked before, doesnt anymore. we need a new bypass :(

**Comment by cgethycx** [comment]
> doesnt work anymore after worlds part 2 update. the game now automatically updates the settings and corrects errors regardless of internet connection. worked before, doesnt anymore. we need a new bypass :(

It does still work. You have to add the whole code at the line stated. You can also add a line with the value=TGA_SHIP1

```
<Property name="UnlockedPlatformRewards">
	<Property name="UnlockedPlatformRewards" value="SW_PREORDER" />
	<Property name="UnlockedPlatformRewards" value="SW_PREORDER2" />
        <Property name="UnlockedPlatformRewards" value="TGA_SHIP1" />
</Property>
```
I claimed offline, saved the game then went online and items were still there.

**Comment by Gir-Thing** [comment]
> It does still work. You have to add the whole code at the line stated. You can also add a line with the value=TGA_SHIP1
> 
> I claimed offline, saved the game then went online and items were still there.

i did add the whole code at the line stated, im not an idiot, it just doesnt work for me... i have checked multiple times, 0 internet connection, hard disconnect. i launch nms, the items are not there to be claimed, i tab out and check the txt document, code has been corrected. i try again, i tab out instantly after launching nms, check the txt document, code is deleted again. its correcting itself instantly after the game launches regardless of internet connection. not sure what version you are using but im using steam.

Either way, i just downloaded the consumerism mod to get the items with quicksilver in the end so i dont need it to work anymore.

**Comment by cgethycx** [comment]
> > It does still work. You have to add the whole code at the line stated. You can also add a line with the value=TGA_SHIP1
> > I claimed offline, saved the game then went online and items were still there.
> 
> i did add the whole code at the line stated, im not an idiot, it just doesnt work for me... i have checked multiple times, 0 internet connection, hard disconnect. i launch nms, the items are not there to be claimed, i tab out and check the txt document, code has been corrected. i try again, i tab out instantly after launching nms, check the txt document, code is deleted again. its correcting itself instantly after the game launches regardless of internet connection. not sure what version you are using but im using steam.
> 
> Either way, i just downloaded the consumerism mod to get the items with quicksilver in the end so i dont need it to work anymore.

Im using the Stem version. Have you updated NMSSaveEditor? 
Definitely not implying you are stupid. Just sharing what worked for me.

**Comment by Gir-Thing** [comment]
> Im using the Stem version. Have you updated NMSSaveEditor? Definitely not implying you are stupid. Just sharing what worked for me.

Oh no no, i wasnt implying that anyone thought i was stupid, i just felt it needed to be said for context given how incredibly simple the original instructions were. 

Yes, my editor was up to date at the time of my original post, its possible there may have been an update between then and now, i dont feel the need to try though given that i solved my problem with a more fulfilling solution, i actually really like the consumerism mod, it adds everything, twitch drops, platform rewards, rare items that cant be obtained in game anymore like the old multitools, and expedition rewards, everything to the quicksilver shop, giving quicksilver so much more value and use, which makes me use the mission terminal a lot more. 

It could also be possible i have a corrupted editor file somewhere, my editor does seem to function weirdly lately, lagging 3x as long when saving, flickering when adding items to inventory, and the twitch drops dont seem to work for me either. i have been using the .bat file to update it since that feature was added, so my install date makes the origin pretty old, i might need to use treesize to completely buzz the existence of it and reinstall fresh.

**Comment by Devilin-Pixy** [comment]
@goatfungus These Switch rewards (`SW_PREORDER` and `SW_PREORDER2`), as well as the recent Starborn Phoenix (`TGA_SHIP1`) from Steam, are still not unlocking through the Account tab. These should be included within the 'UnlockedPlatformRewards' in the GCUSERSETTINGSDATA.MXML file within the game's SETTINGS folder. These will not work if added to the same section in the AccountData.

![Image](https://github.com/user-attachments/assets/90031b7c-1380-465d-b664-ffdda1988cc8)

Would love to see this finally fixed, if possible of course

**Comment by amardito** [comment]
@cgethycx @Gir-Thing 

Apparently the code is need to be updated something like this

```
	<Property name="UnlockedPlatformRewards">
		<Property name="UnlockedPlatformRewards" value="SW_PREORDER" _index="0" />
		<Property name="UnlockedPlatformRewards" value="SW_PREORDER2" _index="1" />
		<Property name="UnlockedPlatformRewards" value="TGA_SHIP1" _index="2" />
	</Property>
```

<img width="1677" height="483" alt="Image" src="https://github.com/user-attachments/assets/96f79e05-dd30-4761-9057-a8075201010c" />

this need to be done on offline mode and while ingame, edit the file

if still doesnt work just exit to main menu and load the same save file

**Comment by kulakovsergei68-byte** [comment]
> [@cgethycx](https://github.com/cgethycx) [@Gir-Thing](https://github.com/Gir-Thing)
> 
> Apparently the code is need to be updated something like this
> 
> ```
> 	<Property name="UnlockedPlatformRewards">
> 		<Property name="UnlockedPlatformRewards" value="SW_PREORDER" _index="0" />
> 		<Property name="UnlockedPlatformRewards" value="SW_PREORDER2" _index="1" />
> 		<Property name="UnlockedPlatformRewards" value="TGA_SHIP1" _index="2" />
> 	</Property>
> ```
> 
> <img alt="Image" width="1677" height="483" src="https://private-user-images.githubusercontent.com/58841477/484072943-96f79e05-dd30-4761-9057-a8075201010c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcxMTc1NDEsIm5iZiI6MTc1NzExNzI0MSwicGF0aCI6Ii81ODg0MTQ3Ny80ODQwNzI5NDMtOTZmNzllMDUtZGQzMC00NzYxLTkwNTctYTgwNzUyMDEwMTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA2VDAwMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjdiODVkOGI3ODgwZjI1NmU3NDYxMTI1ZDczM2IzNWY2MjA2NTc5NDQxMzQ4ODJmNjY2M2ZjZTQ3NTI1ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.05A0bE1Aq6LRaJrc3d-fTk9J8yRT-9sevpM81rO4cHc">
> this need to be done on offline mode and while ingame, edit the file
> 
> if still doesnt work just exit to main menu and load the same save file

Just a HUGE BOW to you! I have spent a hour on it but i did it and it is working! But a tip that helped to me, turn off the connection, put new lines in a file, CLOSE A STEAM, open it again and then open a game! I have tried around 10 times without closing a steam, he was in autonomous mode and it wasnt worked, so before opening the game try to close and reopen the steam!

**Comment by jh4c** [comment]
Another way to make these edits stick (provided they're accurate!) is to temporarily lock the file while the game's launching; this prevents the game from refreshing the file when comparing it to the version stored online (which is what usually kills your edits when entering the game.) Once you reach the point where you can choose which save to load, you can unlock the file, but you may wish to keep it locked until the game's fully loaded; if the edits aren't accurate, the game will exhibit unexpected behaviour when loaded, and may either crash or you may find that everything you thought you knew shows blank because the game's been unable to understand the file, in which case you don't want to risk it overwriting your existing file! (And of course, you should be keeping a backup of anything you edit manually anyway!)

Regarding the _index numbers, while the game sorts everything into alphabetical order when it writes this file, it doesn't care about that when reading it back in, so don't feel you have to go in and manually change all the existing indexes so you can insert whatever your edit is into the alpha-sorted location on the list; just append it with the next highest _index, and the game will sort it into the right location itself when it next saves the file.

**Comment by Alien-user42069** [comment]
i cant find this settings folder where i add the code.. im i just stupis

**Comment by Nicknak13** [comment]
I did this but when I went to redeem it the QS merchant is showing this screen now

<img width="3000" height="4000" alt="Image" src="https://github.com/user-attachments/assets/7ba1a452-89a3-4888-ab63-7027ce668926" />
